export const LOGIN_ROUTE = `${process.env.REACT_APP_USER_API}` + 'login'
export const LOGOUT_ROUTE = `${process.env.REACT_APP_USER_API}` + 'logout'
export const ME_ROUTE = `${process.env.REACT_APP_USER_API}` + 'me'
export const REGISTER_ROUTE = `${process.env.REACT_APP_USER_API}` + 'register'
export const REQUEST_TOKEN_ROUTE = `${process.env.REACT_APP_AUTH_API}` + 'request'
export const GET_ACCESS_TOKEN_ROUTE = `${process.env.REACT_APP_AUTH_API}` + 'token'
export const KEYWORD_POSITIONS_ROUTE = `${process.env.REACT_APP_KEYWORDS_API}` + 'positions'