version: "3.7"

services:
  server:
    build: ./server
    restart: always
    env_file:
      - .env
    ports:
      - "4010:4010"
    depends_on:
      - redis
  postgres:
    build: ./postgres
    restart: always
    volumes:
      - static_data:/var/lib/postgresql/data/pgdata/
    ports:
      - "5432:5432"

volumes:
  static_data:
