version: "3.7"

services:
  server:
    build: ./server
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - "4010:4010"
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - .env
    volumes:
      - static_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  static_data:
